AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a billing alarm with SNS notification.

Resources:
  BillingAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Billing Alarm Topic"
      TopicName: "billing-alarm"

  BillingAlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: "edwinbuike@gmail.com"
      TopicArn: !Ref BillingAlarmTopic

  BillingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmName: "DailyEstimatedCharges"
      AlarmDescription: "This alarm triggers if the daily estimated charges exceed $1."
      ActionsEnabled: true
      AlarmActions: 
        - !Ref BillingAlarmTopic
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: "breaching"
      Metrics: 
        - Id: "m1"
          MetricStat: 
            Metric: 
              Namespace: "AWS/Billing"
              MetricName: "EstimatedCharges"
              Dimensions: 
                - Name: "Currency"
                  Value: "USD"
            Period: 86400
            Stat: "Maximum"
          ReturnData: false
        - Id: "e1"
          Expression: "IF(RATE(m1)>0,RATE(m1)*86400,0)"
          Label: "DailyEstimatedCharges"
          ReturnData: true

Outputs:
  SNSBillingTopicArn:
    Description: "The ARN of the SNS topic for billing alarm"
    Value: !Ref BillingAlarmTopic
